spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/workflow_db
    username: postgres 
    password: 3BK18me028@ 
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
  mail:
    host: smtp.gmail.com
    port: 587
    username: shashankdube4638@gmail.com
    password: impfwbucinrzhlbu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
 
server:
  port: 8081

# Notice that 'app:' is completely flush against the left wall!
app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-ms: 86400000 
  razorpay:
    key-id: rzp_test_Sz56fzICmSu1XC
    key-secret: "NB7GUmRcTq8XGQ5PZbWkd90W"
    
